actors:
  ykmc09_dev:
    image_url: /images/actors/ykmc09_dev.jpg
    name: ykmc09_dev
    url: https://twitter.com/ykmc09_dev
  miuranobuak:
    image_url: /images/actors/miuranobuak.jpg
    name: miuranobuak
    url: https://twitter.com/miuranobuak
  konifar:
    image_url: https://pbs.twimg.com/profile_images/619379391588511744/V4RrXbvM.jpg
    name: konifar
    url: https://twitter.com/konifar
  sezutsu:
    image_url: /images/actors/sezutsu.jpg
    name: Takahito Sezutsu
    url: https://www.facebook.com/sezutsu
  kakakakakku:
    image_url: /images/actors/kakakakakku.jpg
    name: kakakakakku
    url: https://twitter.com/kakakakakku
author: ykmc09_dev, miuranobuak
description: リーン / アジャイルが好きなふたりが、それらについて思いやりを持って語ったり語らなかったりする podcast です。
description_long: リーン / アジャイルが好きな よこみち（@ykmc09_dev） と みうら（@miuranobuak） が、それらについて思いやりを持って語ったり語らなかったりする podcast です。
email: omoiyari.lean.agile@gmail.com
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
hashtag: omoiyarifm
itunes_podcast_url: https://itunes.apple.com/jp/podcast/omoiyari-lean-agile-podcast/id1086384602?mt=2
feedburner_feed_url: http://feeds.lean-agile.fm/omoiyarifm
keywords: lean,agile
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: omoiyari.fm (lean-agile podcast)
url: http://lean-agile.fm
