actors:
  ykmc09:
    image_url: /images/actors/ykmc09.jpg
    name: ykmc09
    url: https://twitter.com/ykmc09
  miuranobuak:
    image_url: /images/actors/miuranobuak.jpg
    name: miuranobuak
    url: https://twitter.com/miuranobuak
  konifar:
    image_url: /images/actors/konifar.jpg
    name: konifar
    url: https://twitter.com/konifar
  sezutsu:
    image_url: /images/actors/sezutsu.jpg
    name: Takahito Sezutsu
    url: https://www.facebook.com/sezutsu
  kakakakakku:
    image_url: /images/actors/kakakakakku.png
    name: kakakakakku
    url: https://twitter.com/kakakakakku
  waysaku:
    image_url: /images/actors/waysaku.jpg
    name: waysaku
    url: https://twitter.com/waysaku
  ktrysmt:
    image_url: /images/actors/ktrysmt.png
    name: ktrysmt
    url: https://twitter.com/ktrysmt
  tomox1001:
    image_url: /images/actors/tomox1001.jpg
    name: tomox1011
    url: https://twitter.com/tomox1001
  hotchemi:
    image_url: /images/actors/hotchemi.png
    name: hotchemi
    url: https://twitter.com/hotchemi
  TAKAKING22:
    image_url: /images/actors/TAKAKING22.jpg
    name: TAKAKING22
    url: https://twitter.com/TAKAKING22
  ama_ch:
    image_url: /images/actors/ama_ch.jpg
    name: ama_ch
    url: https://twitter.com/ama_ch
  satully:
    image_url: /images/actors/satully.jpg
    name: satully
    url: https://twitter.com/satully
  kawaguti:
    image_url: /images/actors/kawaguti.jpg
    name: kawaguti
    url: https://twitter.com/kawaguti
  poohsunny:
    image_url: /images/actors/poohsunny.png
    name: PoohSunny
    url: https://twitter.com/PoohSunny
  kenjiskywalker:
    image_url: /images/actors/kenjiskywalker.jpg
    name: kenjiskywalker
    url: https://twitter.com/kenjiskywalker
  reyabe:
    image_url: /images/actors/reyabe.jpg
    name: reyabe
    url: https://www.facebook.com/rey.abe
  arase:
    image_url: /images/actors/arase.jpg
    name: nakato arase
    url: https://www.facebook.com/nakato.arase
  takoratta:
    image_url: /images/actors/takoratta.jpg
    name: takoratta
    url: https://twitter.com/takoratta
author: ykmc09, miuranobuak
description: リーン / アジャイルが好きなふたりが、それらについて思いやりを持って語ったり語らなかったりする Podcast です。
description_long: リーン / アジャイルが好きな よこみち（@ykmc09） と みうら（@miuranobuak） が、それらについて思いやりを持って語ったり語らなかったりする Podcast です。
email: omoiyari.lean.agile@gmail.com
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
hashtag: omoiyarifm
itunes_podcast_url: https://itunes.apple.com/jp/podcast/omoiyari-lean-agile-podcast/id1086384602?mt=2
feedburner_feed_url: http://feeds.lean-agile.fm/omoiyarifm
keywords: lean,agile
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: omoiyari.fm (lean-agile podcast) &#35;omoiyarifm
url: https://lean-agile.fm
